#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/OpenWheels.jar:$APPDIR/lib/core.jar:$APPDIR/lib/controlP5.jar:$APPDIR/lib/RXTXcomm.jar:$APPDIR/lib/serial.jar" OpenWheels
